# Generated by Django 6.1.1 on 2026-09-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsContactMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('is_resolved', models.BooleanField()),
            ],
            options={
                'db_table': 'cms_contactmessage',
            },
        ),
        migrations.CreateModel(
            name='CmsHomepageBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=254)),
                ('link_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('order', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cms_homepagebanner',
            },
        ),
    ]
