# Generated by Django 6.1.1 on 2026-09-27 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsDeviceToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_ref', models.BigIntegerField(db_index=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifications_devicetoken',
            },
        ),
        migrations.CreateModel(
            name='ShippingShipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_ref', models.BigIntegerField(db_index=True, unique=True)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('courier', models.CharField(default='J&T Express', max_length=64)),
                ('waybill_no', models.CharField(max_length=64)),
                ('tracking_no', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipping_shipment',
            },
        ),
        migrations.CreateModel(
            name='ShippingShippingZone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fee', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_shippingzone',
            },
        ),
        migrations.CreateModel(
            name='NotificationsNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_ref', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('order_ref', models.BigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifications_notification',
                'indexes': [models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['customer_ref', 'is_read'], name='notificatio_custome_fba12e_idx')],
            },
        ),
    ]
