# Generated by Django 6.1.1 on 2026-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsContactMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cms_contactmessage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsHomepageBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(default='/assets/banners/default.jpg', max_length=254)),
                ('link_url', models.CharField(default='/shop', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'cms_homepagebanner',
                'ordering': ['order', 'id'],
            },
        ),
    ]
