# Generated by Django 6.1.1 on 2026-09-27 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('customer_ref', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending_stock_confirmation', max_length=32)),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOutboxMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=48)),
                ('payload', models.JSONField()),
                ('state', models.CharField(db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('correlation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_outboxmessage',
            },
        ),
        migrations.CreateModel(
            name='ReviewsReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=255)),
                ('customer_ref', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('product_ref', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField()),
                ('merchant_reply', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdersIdempotencyRecord',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_idempotencyrecord',
            },
        ),
        migrations.CreateModel(
            name='OrdersOrderLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_ref', models.BigIntegerField(db_index=True)),
                ('variant_ref', models.BigIntegerField(db_index=True)),
                ('sku_snapshot', models.CharField(default='', max_length=64)),
                ('product_name_snapshot', models.CharField(default='', max_length=255)),
                ('variant_desc_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_orderline',
            },
        ),
        migrations.CreateModel(
            name='OrdersPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending_collection', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('provider_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_payment',
            },
        ),
        migrations.CreateModel(
            name='OrdersShippingAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='PH', max_length=2)),
                ('phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_shippingaddress',
            },
        ),
        migrations.CreateModel(
            name='OrdersStockHold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkout_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('state', models.CharField(default='active', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_holds', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_stockhold',
            },
        ),
    ]
