# Generated by Django 6.1.1 on 2026-09-27 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('addresses', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(db_index=True, default='customer', max_length=16)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_customer',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=150)),
                ('actor_role', models.CharField(default='admin', max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreServiceEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_model', models.CharField(max_length=100)),
                ('target_field', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_serviceevent',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='identity.accountscustomer')),
            ],
            options={
                'db_table': 'identity_authtoken',
            },
        ),
        migrations.CreateModel(
            name='AccountsWishlistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_ref', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='identity.accountscustomer')),
            ],
            options={
                'db_table': 'accounts_wishlistitem',
                'constraints': [models.UniqueConstraint(fields=('customer', 'product_ref'), name='uniq_wishlist_entry')],
            },
        ),
    ]
