# Generated by Django 6.1.1 on 2026-09-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('addresses', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('role', models.CharField(db_index=True, max_length=16)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts_customer',
            },
        ),
        migrations.CreateModel(
            name='CoreServiceEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_model', models.CharField(max_length=100)),
                ('target_field', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_serviceevent',
                'indexes': [models.Index(fields=['completed_at'], name='core_servic_complet_c56b9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountsWishlistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_ref', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='identity.accountscustomer')),
            ],
            options={
                'db_table': 'accounts_wishlistitem',
                'constraints': [models.UniqueConstraint(fields=('customer', 'product_ref'), name='uniq_wishlist_entry')],
            },
        ),
    ]
