# Generated by Django 6.1.1 on 2026-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_seed_test_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=150)),
                ('actor_role', models.CharField(default='admin', max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity_auditlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
