# Generated by Django 6.1.1 on 2026-09-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders_order',
                'indexes': [models.Index(fields=['customer_id'], name='orders_orde_custome_59b6fb_idx'), models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrdersOrderLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.ordersorder')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='catalog.catalogproduct')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'orders_orderline',
            },
        ),
        migrations.CreateModel(
            name='OrdersOrderLineInventorySequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('next_sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('orderline', models.OneToOneField(db_column='orderline_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sequence', to='orders.ordersorderline')),
            ],
            options={
                'db_table': 'orders_orderlineinventorysequence',
            },
        ),
        migrations.CreateModel(
            name='OrdersOrderMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_ordermessage',
            },
        ),
        migrations.CreateModel(
            name='OrdersPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('provider_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_payment',
            },
        ),
        migrations.CreateModel(
            name='OrdersShippingAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'orders_shippingaddress',
            },
        ),
        migrations.CreateModel(
            name='ServicesService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='orders.ordersorder')),
            ],
            options={
                'db_table': 'services_service',
            },
        ),
        migrations.AddConstraint(
            model_name='ordersorderline',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'variant'), name='uniq_order_product_variant'),
        ),
        migrations.AddIndex(
            model_name='orderspayment',
            index=models.Index(fields=['order', 'status'], name='orders_paym_order_i_e3de73_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesservice',
            index=models.Index(fields=['type'], name='services_se_type_1f71f5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesservice',
            index=models.Index(fields=['status'], name='services_se_status_288ecc_idx'),
        ),
    ]
