# Generated by Django 6.1.1 on 2026-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordersshippingaddress_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=255)),
                ('customer_ref', models.BigIntegerField(blank=True, null=True)),
                ('product_ref', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
            },
        ),
    ]
