# Generated by Django 6.1.1 on 2026-09-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_reviewsreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsreview',
            name='merchant_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewsreview',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
