# Generated by Django 6.1.1 on 2026-10-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_checkout_lookup_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersorderline',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordersorderline',
            name='sku_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordersorderline',
            name='variant_desc_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='OrdersPaymentTransition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_type', models.CharField(max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transitions', to='orders.ordersorder')),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='orders.orderspayment')),
            ],
            options={
                'db_table': 'orders_paymenttransition',
                'indexes': [models.Index(fields=['payment', 'created_at'], name='orders_paym_payment_7ce8c2_idx'), models.Index(fields=['order', 'created_at'], name='orders_paym_order_i_8c372c_idx'), models.Index(fields=['to_status'], name='orders_paym_to_stat_008a53_idx')],
            },
        ),
    ]
