
-- db_identity
CREATE TABLE accounts_customer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password        VARCHAR(128)    NOT NULL,
    last_login      TIMESTAMP(6)     NULL,
    is_superuser    BOOLEAN            NOT NULL,
    email           VARCHAR(254)    NOT NULL,
    name            VARCHAR(150)    NOT NULL,
    phone           VARCHAR(32)     NOT NULL,
    addresses       JSONB            NOT NULL,
    is_active       BOOLEAN            NOT NULL,
    role            VARCHAR(16)     NOT NULL,
    date_joined     TIMESTAMP(6)     NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uniq_email UNIQUE (email)
);

CREATE TABLE accounts_wishlistitem (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id     BIGINT          NOT NULL,
    product_ref     BIGINT          NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT fk_customer_id 
        FOREIGN KEY (customer_id) REFERENCES accounts_customer(id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_wishlist_entry UNIQUE (customer_id, product_ref)
);

CREATE TABLE core_serviceevent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    target_model    VARCHAR(100)    NOT NULL,
    target_field    VARCHAR(100)    NOT NULL,
    reference_id    BIGINT          NOT NULL,
    operation       VARCHAR(8)      NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL,
    completed_at    TIMESTAMP(6)     NULL,
    attempts        INTEGER    NOT NULL DEFAULT 0,
    last_error      TEXT        NULL,

    PRIMARY KEY (id)
);

-- db_catalog
CREATE TABLE catalog_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(120)    NOT NULL,
    slug        VARCHAR(140)    NOT NULL,
    parent_id   BIGINT          NULL,

    PRIMARY KEY (id),
    CONSTRAINT uniq_category_slug UNIQUE (slug),
    CONSTRAINT uniq_category_sibling UNIQUE (parent_id, name),
    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_id) REFERENCES catalog_category(id)
        ON DELETE SET NULL
);

CREATE TABLE catalog_product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(200)    NOT NULL,
    slug            VARCHAR(220)    NOT NULL,
    description     TEXT        NOT NULL,
    category_id     BIGINT          NOT NULL,
    base_price      INTEGER    NOT NULL DEFAULT 0,
    images          JSONB            NOT NULL,
    is_active       BOOLEAN            NOT NULL,
    is_mock         BOOLEAN            NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT uniq_product_slug UNIQUE (slug),
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES catalog_category(id)
        ON DELETE RESTRICT
);

CREATE TABLE catalog_productvariant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id      BIGINT          NOT NULL,
    sku             VARCHAR(64)     NOT NULL,
    size            VARCHAR(4)      NOT NULL,
    color           VARCHAR(40)     NOT NULL,
    fit             VARCHAR(10)     NOT NULL,
    price_override  INTEGER    NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_productvariant_product
        FOREIGN KEY (product_id) REFERENCES catalog_product(id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_productvariant_sku UNIQUE (sku),
    CONSTRAINT uniq_variant_axes UNIQUE (product_id, size, color, fit)
);

CREATE TABLE inventory_stockrecord (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    variant_id      BIGINT          NOT NULL,
    qty_on_hand     INTEGER    NOT NULL DEFAULT 0,
    qty_reserved    INTEGER    NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER NOT NULL DEFAULT 5,

    PRIMARY KEY (id),
    CONSTRAINT fk_stockrecord_variant
        FOREIGN KEY (variant_id) REFERENCES catalog_productvariant(id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_stock_variant UNIQUE (variant_id)
);

CREATE TABLE inventory_reservation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    variant_id      BIGINT          NOT NULL,
    qty             INTEGER    NOT NULL DEFAULT 0,
    status          VARCHAR(9)      NOT NULL,
    session_key     VARCHAR(64)     NOT NULL,
    checkout_id     VARCHAR(64)     NOT NULL,
    order_ref       BIGINT          NULL,
    expires_at      TIMESTAMP(6)     NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ended_at        TIMESTAMP(6)     NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_reservation_variant
        FOREIGN KEY (variant_id) REFERENCES catalog_productvariant(id)
        ON DELETE RESTRICT
);

CREATE TABLE inventory_idempotencyrecord (
    key_hash            VARCHAR(64)     NOT NULL,
    request_fingerprint VARCHAR(64)     NOT NULL,
    status_code         SMALLINT NOT NULL,
    response_body       JSONB            NOT NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (key_hash)
);

CREATE TABLE inventory_stockmovement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    variant_id      BIGINT          NOT NULL,
    delta           INT             NOT NULL,
    reason          VARCHAR(12)     NOT NULL,
    ref_order_ref   BIGINT          NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT fk_stockmovement_variant
        FOREIGN KEY (variant_id) REFERENCES catalog_productvariant(id)
        ON DELETE RESTRICT
);

-- db_orders
CREATE TABLE orders_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_no        VARCHAR(20)     NOT NULL,
    customer_ref    BIGINT          NULL,
    status          VARCHAR(10)     NOT NULL DEFAULT 'pending',
    subtotal        INTEGER    NOT NULL DEFAULT 0,
    shipping_fee    INTEGER    NOT NULL DEFAULT 0,
    total           INTEGER    NOT NULL DEFAULT 0,
    shipping_address JSONB           NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT uniq_order_no UNIQUE (order_no)
);

CREATE TABLE orders_orderitem (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id                BIGINT          NOT NULL,
    variant_ref             BIGINT          NOT NULL,
    qty                     INTEGER    NOT NULL DEFAULT 1,
    unit_price_snapshot     INTEGER    NOT NULL,
    product_ref             BIGINT          NOT NULL,
    sku_snapshot            VARCHAR(64)     NOT NULL,
    product_name_snapshot   VARCHAR(200)    NOT NULL,
    product_slug_snapshot   VARCHAR(220)    NOT NULL,
    size_snapshot           VARCHAR(4)      NOT NULL,
    color_snapshot          VARCHAR(40)     NOT NULL,
    fit_snapshot            VARCHAR(10)     NOT NULL,
    image_url_snapshot      VARCHAR(2048)   NOT NULL,
    snapshot_source         VARCHAR(16)     NOT NULL DEFAULT 'checkout',
    created_at              TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT fk_orderitem_order
        FOREIGN KEY (order_id) REFERENCES orders_order(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_orderitem_variant
        FOREIGN KEY (variant_ref) REFERENCES catalog_productvariant(id)
        ON DELETE RESTRICT,
    CONSTRAINT uniq_order_variant UNIQUE (order_id, variant_ref)
);

CREATE TABLE orders_ordernumbersequence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    year        INTEGER    NOT NULL,
    last_value  INTEGER    NOT NULL DEFAULT 0,

    PRIMARY KEY (id),
    CONSTRAINT uniq_year UNIQUE (year)
);

CREATE TABLE orders_stockhold (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id        BIGINT          NOT NULL,
    checkout_id     VARCHAR(64)     NOT NULL,
    state           VARCHAR(9)      NOT NULL DEFAULT 'active',
    expires_at      TIMESTAMP(6)     NOT NULL,
    committed_at    TIMESTAMP(6)     NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT fk_stockhold_order
        FOREIGN KEY (order_id) REFERENCES orders_order(id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_checkout UNIQUE (checkout_id)
);

CREATE TABLE orders_outboxmessage (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    topic           VARCHAR(48)     NOT NULL,
    payload         JSONB            NOT NULL,
    state           VARCHAR(7)      NOT NULL DEFAULT 'pending',
    attempts        SMALLINT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    correlation_id  VARCHAR(128)    NULL,
    last_error      TEXT        NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    sent_at         TIMESTAMP(6)     NULL,

    PRIMARY KEY (id)
);

CREATE TABLE payments_payment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id        BIGINT          NOT NULL,
    provider_ref    VARCHAR(128)    NULL,
    method          VARCHAR(8)      NOT NULL,
    status          VARCHAR(10)     NOT NULL DEFAULT 'pending',
    amount          INTEGER    NOT NULL,
    paid_at         TIMESTAMP(6)     NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id) REFERENCES orders_order(id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_provider_ref UNIQUE (provider_ref),
    CONSTRAINT uniq_order_payment UNIQUE (order_id)
);

CREATE TABLE reviews_review (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_ref    BIGINT          NOT NULL,
    product_ref     BIGINT          NOT NULL,
    order_id        BIGINT          NOT NULL,
    rating          SMALLINT NOT NULL,
    body            TEXT        NOT NULL DEFAULT '',
    status          VARCHAR(10)     NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT fk_review_customer
        FOREIGN KEY (customer_ref) REFERENCES accounts_customer(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_review_product
        FOREIGN KEY (product_ref) REFERENCES catalog_product(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_review_order
        FOREIGN KEY (order_id) REFERENCES orders_order(id)
        ON DELETE RESTRICT,
    CONSTRAINT uniq_customer_product UNIQUE (customer_ref, product_ref)
);

-- db_fulfillment
CREATE TABLE shipping_shippingzone (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(50)     NOT NULL,
    fee         INTEGER    NOT NULL DEFAULT 0,
    is_active   BOOLEAN            NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uniq_zone_name UNIQUE (name)
);

CREATE TABLE shipping_shipment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_ref       BIGINT          NOT NULL,
    courier         VARCHAR(20)     NOT NULL,
    waybill_no      VARCHAR(64)     NOT NULL,
    tracking_url    VARCHAR(254)    NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending',
    booked_at       TIMESTAMP(6)     NULL,

    PRIMARY KEY (id),
    CONSTRAINT uniq_shipment_order UNIQUE (order_ref)
);

CREATE TABLE notifications_devicetoken (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_ref    BIGINT          NOT NULL,
    token           VARCHAR(200)    NOT NULL,
    platform        VARCHAR(10)     NOT NULL,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_seen_at    TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT fk_devicetoken_customer
        FOREIGN KEY (customer_ref) REFERENCES accounts_customer(id)
        ON DELETE CASCADE,
    CONSTRAINT uniq_token_platform UNIQUE (token, platform)
);

CREATE TABLE notifications_notification (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_ref    BIGINT          NOT NULL,
    title           VARCHAR(140)    NOT NULL,
    body            TEXT        NOT NULL,
    category        VARCHAR(10)     NOT NULL,
    order_ref       BIGINT          NULL,
    is_read         BOOLEAN            NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT fk_notification_customer
        FOREIGN KEY (customer_ref) REFERENCES accounts_customer(id)
        ON DELETE CASCADE
);

-- db_content
CREATE TABLE cms_homepagebanner (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(200)    NOT NULL,
    image_url   VARCHAR(254)    NOT NULL,
    link_url    VARCHAR(200)    NOT NULL,
    is_active   BOOLEAN            NOT NULL DEFAULT TRUE,
    "order"     SMALLINT NOT NULL DEFAULT 0,

    PRIMARY KEY (id)
);

CREATE TABLE cms_contactmessage (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(150)    NOT NULL,
    email       VARCHAR(254)    NOT NULL,
    message     TEXT        NOT NULL,
    is_resolved BOOLEAN            NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id)
);

-- PostgreSQL indexes converted from MySQL INDEX definitions
CREATE INDEX idx_role ON accounts_customer (role);
CREATE INDEX idx_product_ref ON accounts_wishlistitem (product_ref);
CREATE INDEX idx_parent_slug ON catalog_category (parent_id, slug);
CREATE INDEX idx_mock ON catalog_product (is_mock);
CREATE INDEX idx_product_id ON catalog_productvariant (product_id);
CREATE INDEX idx_variant_id ON inventory_stockrecord (variant_id);
CREATE INDEX idx_status_expires ON inventory_reservation (status, expires_at);
CREATE INDEX idx_checkout_id ON inventory_reservation (checkout_id);
CREATE INDEX idx_created_at ON inventory_idempotencyrecord (created_at);
CREATE INDEX idx_ref_order_ref ON inventory_stockmovement (ref_order_ref);
CREATE INDEX idx_variant_created ON inventory_stockmovement (variant_id, created_at);
CREATE INDEX idx_customer_ref ON orders_order (customer_ref);
CREATE INDEX idx_status ON orders_order (status);
CREATE INDEX idx_product_ref ON orders_orderitem (product_ref);
CREATE INDEX idx_order_created ON orders_orderitem (order_id, created_at);
CREATE INDEX idx_state_expires ON orders_stockhold (state, expires_at);
CREATE INDEX idx_dispatch ON orders_outboxmessage (state, next_attempt_at);
CREATE INDEX idx_correlation ON orders_outboxmessage (correlation_id);
CREATE INDEX idx_provider_ref ON payments_payment (provider_ref);
CREATE INDEX idx_product_reviews ON reviews_review (product_ref, status);
CREATE INDEX idx_customer_reviews ON reviews_review (customer_ref, created_at);
CREATE INDEX idx_order_ref ON shipping_shipment (order_ref);
CREATE INDEX idx_courier ON shipping_shipment (courier);
CREATE INDEX idx_customer_token ON notifications_devicetoken (customer_ref, platform);
CREATE INDEX idx_inbox ON notifications_notification (customer_ref, is_read, created_at);
CREATE INDEX idx_order_active ON cms_homepagebanner ("order", is_active);
CREATE INDEX idx_resolved ON cms_contactmessage (is_resolved, created_at);
