# Generated by Django 6.1.1 on 2026-09-27 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIdempotencyRecord',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventory_idempotencyrecord',
            },
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_category',
            },
        ),
        migrations.CreateModel(
            name='CatalogColor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'catalog_color',
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_catalog_color_name'), models.UniqueConstraint(fields=('hex_code',), name='uniq_catalog_color_hex')],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('base_price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_product',
            },
        ),
        migrations.CreateModel(
            name='CatalogProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('attributes', models.JSONField(default=dict)),
                ('price_adjustment', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('color', models.ForeignKey(blank=True, db_column='color_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.catalogcolor')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.catalogproduct')),
            ],
            options={
                'db_table': 'catalog_product_variant',
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkout_id', models.CharField(db_index=True, max_length=64)),
                ('order_ref', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.catalogproduct')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_reservation',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warehouse_id', models.BigIntegerField(default=1)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('last_counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='catalog.catalogproduct')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_stockentry',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=20)),
                ('ref_order_ref', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_category_parent_slug'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['checkout_id', 'status'], name='inventory_r_checkou_63daee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['expires_at', 'status'], name='inventory_r_expires_0a2d45_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystockentry',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'warehouse_id'), name='uniq_stock_product_variant_warehouse'),
        ),
    ]
