# Generated by Django 6.1.1 on 2026-09-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_idempotencyrecord',
            },
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_category',
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField()),
                ('is_featured', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_product',
            },
        ),
        migrations.CreateModel(
            name='CatalogProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('attributes', models.JSONField()),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.catalogproduct')),
            ],
            options={
                'db_table': 'catalog_product_variant',
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.catalogproduct')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_reservation',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warehouse_id', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('last_counted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='catalog.catalogproduct')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_stockentry',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warehouse_id', models.BigIntegerField()),
                ('quantity_change', models.IntegerField()),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=100)),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_events', to='catalog.catalogproduct')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_events', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_stockevent',
            },
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_category_parent_slug'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['expires_at'], name='inventory_r_expires_485198_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystockentry',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'warehouse_id'), name='uniq_stock_product_variant_warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventorystockevent',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_043fc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystockevent',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'warehouse_id', 'created_at'), name='uniq_stockevent_product_variant_warehouse_created'),
        ),
    ]
