# Generated by Django 6.1.1 on 2026-09-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField()),
                ('category_id', models.BigIntegerField()),
                ('base_price', models.PositiveIntegerField()),
                ('images', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('is_mock', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog_product',
            },
        ),
    ]
