# Generated by Django 6.1.1 on 2026-09-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
