# Generated by Django 6.1.1 on 2026-09-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='base_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_category',
            },
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.catalogcategory'),
        ),
    ]
