# Generated by Django 6.1.1 on 2026-09-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_catalogproduct_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('size', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=40)),
                ('fit', models.CharField(max_length=10)),
                ('price_override', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.catalogproduct')),
            ],
            options={
                'db_table': 'catalog_productvariant',
                'constraints': [models.UniqueConstraint(fields=('product', 'size', 'color', 'fit'), name='uniq_variant_axes')],
            },
        ),
    ]
