# Generated by Django 6.1.1 on 2026-09-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogproductvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsContactMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms_contactmessage',
            },
        ),
        migrations.CreateModel(
            name='CmsHomepageBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=254)),
                ('link_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_homepagebanner',
            },
        ),
        migrations.CreateModel(
            name='InventoryIdempotencyRecord',
            fields=[
                ('key_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status_code', models.SmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_idempotencyrecord',
            },
        ),
        migrations.CreateModel(
            name='NotificationsNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_ref', models.BigIntegerField()),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=10)),
                ('order_ref', models.BigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications_notification',
            },
        ),
        migrations.CreateModel(
            name='OrdersOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=20, unique=True)),
                ('customer_ref', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('shipping_address', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders_order',
            },
        ),
        migrations.CreateModel(
            name='OrdersOrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
                ('last_value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'orders_ordernumbersequence',
            },
        ),
        migrations.CreateModel(
            name='OrdersOutboxMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=48)),
                ('payload', models.JSONField()),
                ('state', models.CharField(default='pending', max_length=7)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_outboxmessage',
            },
        ),
        migrations.CreateModel(
            name='ShippingShipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_ref', models.BigIntegerField(unique=True)),
                ('courier', models.CharField(max_length=20)),
                ('waybill_no', models.CharField(max_length=64)),
                ('tracking_url', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipping_shipment',
            },
        ),
        migrations.CreateModel(
            name='ShippingShippingZone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fee', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_shippingzone',
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=9)),
                ('session_key', models.CharField(max_length=64)),
                ('checkout_id', models.CharField(max_length=64)),
                ('order_ref', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_reservation',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=12)),
                ('ref_order_ref', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_stockmovement',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty_on_hand', models.IntegerField(default=0)),
                ('qty_reserved', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('variant', models.OneToOneField(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_record', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_stockrecord',
            },
        ),
        migrations.CreateModel(
            name='NotificationsDeviceToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_ref', models.BigIntegerField()),
                ('token', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications_devicetoken',
                'constraints': [models.UniqueConstraint(fields=('token', 'platform'), name='uniq_token_platform')],
            },
        ),
        migrations.CreateModel(
            name='OrdersStockHold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkout_id', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(default='active', max_length=9)),
                ('expires_at', models.DateTimeField()),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_holds', to='catalog.ordersorder')),
            ],
            options={
                'db_table': 'orders_stockhold',
            },
        ),
        migrations.CreateModel(
            name='PaymentsPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('method', models.CharField(max_length=8)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('amount', models.IntegerField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='catalog.ordersorder')),
            ],
            options={
                'db_table': 'payments_payment',
            },
        ),
        migrations.CreateModel(
            name='OrdersOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price_snapshot', models.IntegerField()),
                ('product_ref', models.BigIntegerField()),
                ('sku_snapshot', models.CharField(max_length=64)),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('product_slug_snapshot', models.CharField(max_length=220)),
                ('size_snapshot', models.CharField(max_length=4)),
                ('color_snapshot', models.CharField(max_length=40)),
                ('fit_snapshot', models.CharField(max_length=10)),
                ('image_url_snapshot', models.CharField(max_length=2048)),
                ('snapshot_source', models.CharField(default='checkout', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.ordersorder')),
                ('variant_ref', models.ForeignKey(db_column='variant_ref', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'orders_orderitem',
                'constraints': [models.UniqueConstraint(fields=('order', 'variant_ref'), name='uniq_order_variant')],
            },
        ),
        migrations.CreateModel(
            name='ReviewsReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_ref', models.BigIntegerField()),
                ('rating', models.SmallIntegerField()),
                ('body', models.TextField(default='')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='catalog.ordersorder')),
                ('product_ref', models.ForeignKey(db_column='product_ref', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.catalogproduct')),
            ],
            options={
                'db_table': 'reviews_review',
                'constraints': [models.UniqueConstraint(fields=('customer_ref', 'product_ref'), name='uniq_customer_product')],
            },
        ),
    ]
