# Generated by Django 6.1.1 on 2026-09-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seed_product_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogColor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog_color',
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_catalog_color_name'), models.UniqueConstraint(fields=('hex_code',), name='uniq_catalog_color_hex')],
            },
        ),
        migrations.AddField(
            model_name='catalogproductvariant',
            name='color',
            field=models.ForeignKey(blank=True, db_column='color_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.catalogcolor'),
        ),
    ]
