# Generated by Django 6.1.1 on 2026-09-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_seed_inventory_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=20)),
                ('ref_order_ref', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.catalogproductvariant')),
            ],
            options={
                'db_table': 'inventory_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
    ]
